### ISSUE TITLE
RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by dwt189** [lucastabelini/LaneATT#2]
Thanks for sharing your work! I followed your instructions and created a conda environment as required.

> python main.py test --exp_name laneatt_r34_culane

gives the following error:

Traceback (most recent call last):
  File "main.py", line 62, in <module>
    main()
  File "main.py", line 58, in main
    runner.eval(epoch=args.epoch or exp.get_last_checkpoint_epoch(), save_predictions=args.save_predictions)
  File "/home/ms/Desktop/LaneATT/lib/runner.py", line 92, in eval
    output = model(images, **test_parameters)
  File "/home/ms/miniconda3/envs/laneatt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ms/Desktop/LaneATT/lib/models/laneatt.py", line 110, in forward
    proposals_list = self.nms(reg_proposals, attention_matrix, nms_thres, nms_topk, conf_threshold)
  File "/home/ms/Desktop/LaneATT/lib/models/laneatt.py", line 133, in nms
    proposals = proposals[keep]
RuntimeError: CUDA error: invalid device function
Segmentation fault (core dumped)

What should I change to run the code?

**Comment by lucastabelini** [comment]
What version of PyTorch and CUDA is installed?

**Comment by dwt189** [comment]
PyTorch 1.6 and CUDA toolkit 10.2. 
And there is only one GPU on my PC.

**Comment by lucastabelini** [comment]
I experienced this error when the CUDA version used by PyTorch and the one used to compile the NMS module were different. Is CUDA 10.2 the version installed in the system? (e.g., in /usr/local/cuda-10.2)

**Comment by dwt189** [comment]
Indeed they are different. I thought the NMS module would be compiled by CUDA 10.2 in conda environment.
Thank you!

**Comment by lucastabelini** [comment]
Yeah, I was unable to find a way to compile the NMS module using the CUDA version installed using conda and I am sure this will confuse future users of the code. Please let me know if you find a way.

**Comment by k8280627** [comment]
Hi @lucastabelini ,

Thank you very much for your work! I also encountered the same issue, but my CUDA version is 10.0. I have a couple questions that I'd like to ask:
1. Is it necessary to use CUDA version 10.2? 
2. How do I check if NMS module is using the same CUDA version as the one that Pytorch uses?

Thank you!

**Comment by lucastabelini** [comment]
@k8280627:
1. Not really. I just can't guarantee that the results I obtained are going to be exactly the same for the given pretrained models. When I tried testing with a different PyTorch version (with a different CUDA version) the results did not match exactly, but the PyTorch version mismatch (between the installed one and the one used to train the model) could have caused it.
2. The NMS module will be compiled using your global installation of CUDA (e.g., `/usr/local/cuda`) while each PyTorch uses a different version. In conda there are multiple versions of PyTorch each with a different CUDA version. For example, you could install PyTorch with CUDA 10.1 using `conda install pytorch  cudatoolkit=10.1 -c pytorch`. However, I don't think any of the latest PyTorch versions are compiled using CUDA 10.0.

**Comment by k8280627** [comment]
@lucastabelini 

I see. I think the version mismatch is definitely the issue. Thank you very much for your fast and helpful response!

**Comment by HaoYongqiang1999** [comment]
@lucastabelini 
Thank you for your wonderful work.
I work on a GPU server and I am not a root user. There are three versions of CUDA (9.0, 10.0, 10.1) under the server's `/usr/local/` path. How can I specify to use CUDA 10.1 instead of  9.0 or 10.0 to compile the NMS?

**Comment by HaoYongqiang1999** [comment]
> @lucastabelini
> Thank you for your wonderful work.
> I work on a GPU server and I am not a root user. There are three versions of CUDA (9.0, 10.0, 10.1) under the server's `/usr/local/` path. How can I specify to use CUDA 10.1 instead of 9.0 or 10.0 to compile the NMS?

I have solved my problem by entering the following code in the terminal：
`export CUDA_HOME=/usr/local/cuda-10.1/
export PATH=$PATH:/usr/local/cuda-10.1/bin/`

**Comment by HaoYongqiang1999** [comment]
> @lucastabelini
> Thank you for your wonderful work.
> I work on a GPU server and I am not a root user. There are three versions of CUDA (9.0, 10.0, 10.1) under the server's `/usr/local/` path. How can I specify to use CUDA 10.1 instead of 9.0 or 10.0 to compile the NMS?

I have solved my problem by entering the following code in the terminal：
`export CUDA_HOME=/usr/local/cuda-10.1/; export PATH=$PATH:/usr/local/cuda-10.1/bin/`
